"""Security testing tools exposed to CrewAI agents."""
from .security_tools import (
    scan_website_tool,
    analyze_headers_tool,
    test_http_methods_tool,
    discover_api_endpoints_tool,
    enumerate_directories_tool,
    info_disclosure_tool,
    render_page_tool,
    discover_forms_tool,
    explore_click_targets_tool,
    stateful_explore_tool,
    screenshot_tool,
    sqli_test_tool,
    xss_test_tool,
    csrf_check_tool,
    cors_check_tool,
    auth_bypass_tool,
    fuzz_parameter_tool,
    form_fuzz_tool,
    check_admin_endpoints_tool,
    sitemap_tool,
    api_key_leak_scan_tool,
    jwt_decode_tool,
)

ALL_TOOLS = [
    scan_website_tool,
    analyze_headers_tool,
    test_http_methods_tool,
    discover_api_endpoints_tool,
    enumerate_directories_tool,
    info_disclosure_tool,
    render_page_tool,
    discover_forms_tool,
    explore_click_targets_tool,
    stateful_explore_tool,
    screenshot_tool,
    sqli_test_tool,
    xss_test_tool,
    csrf_check_tool,
    cors_check_tool,
    auth_bypass_tool,
    fuzz_parameter_tool,
    form_fuzz_tool,
    check_admin_endpoints_tool,
    sitemap_tool,
    api_key_leak_scan_tool,
    jwt_decode_tool,
]

__all__ = ["ALL_TOOLS"]
